-- Rebrand to Needa Beauty Lab (nails-only).
-- The seed never overwrites existing rows, so already-seeded databases keep
-- the old name without this migration. Every UPDATE is guarded on the exact
-- previously seeded value: anything the admin has edited is left untouched,
-- and re-running it is a no-op.
UPDATE `site_settings` SET `business_name` = 'Needa Beauty Lab' WHERE `id` = 1 AND `business_name` = 'Makeup by Needa';--> statement-breakpoint
UPDATE `site_settings` SET `home_title` = 'Needa Beauty Lab | Toronto Nail Technician' WHERE `id` = 1 AND `home_title` = 'Makeup by Needa | Toronto Makeup Artist';--> statement-breakpoint
UPDATE `site_settings` SET `home_description` = 'Premium nail services in Toronto, Canada — gel polish, extensions, nail art, premium finishes and signature sets.' WHERE `id` = 1 AND `home_description` = 'Makeup, hair and nail artistry in Toronto, Canada.';--> statement-breakpoint
UPDATE `site_settings` SET `footer_text` = 'Needa Beauty Lab. All rights reserved.' WHERE `id` = 1 AND `footer_text` = 'Makeup by Needa. All rights reserved.';--> statement-breakpoint
UPDATE `site_settings` SET `whatsapp_message` = 'Hi Needa Beauty Lab, I’d like to enquire about your nail services.' WHERE `id` = 1 AND `whatsapp_message` = 'Hi Makeup by Needa, I’d like to enquire about your services.';--> statement-breakpoint
UPDATE `artist_profile` SET `short_bio` = 'A personal approach to nail care and nail design, thoughtfully shaped around your style, your occasion, and the way you want to feel.' WHERE `id` = 1 AND `short_bio` = 'A personal approach to makeup, hair styling, and nail art, thoughtfully designed around your features, your occasion, and the way you want to feel.';--> statement-breakpoint
UPDATE `artist_profile` SET `bio` = 'Hi, I''m Needa — the nail technician behind Needa Beauty Lab in Toronto. My work is built around a simple belief: beauty should feel personal, never templated.\n\nEvery appointment begins with a conversation — your style, your occasion, your preferred length and shape, and the finish you have in mind. From there, each set is designed around you: a clean gel manicure, soft French tips, glossy chrome or cat eye, lightweight extensions, or detailed nail art finished with charms and 3D details.\n\nWhether it is an everyday refresh, a celebration, or a special event, the intention stays the same — a polished, long-lasting finish that still feels entirely like you.' WHERE `id` = 1 AND `bio` = 'Hi, I''m Needa — a makeup, hair and nail artist based in Toronto. My work is built around a simple belief: beauty should feel personal, never templated.\n\n\n\nEvery appointment begins with a conversation — your occasion, your features, your outfit, and above all, the way you want to feel when you walk out the door. From there, the look is designed around you: softly luminous bridal makeup, defined evening glamour, romantic waves, sleek finished hair, or nail art detailed to complete the story.\n\n\n\nWhether it is your wedding morning, an engagement celebration, a reception, or a portrait session, the intention stays the same — a polished, enduring finish that still feels entirely like you.';--> statement-breakpoint
UPDATE `artist_profile` SET `instagram` = '@nailsbyneeda' WHERE `id` = 1 AND `instagram` = '@makeupbynee_';--> statement-breakpoint
UPDATE `gallery_items` SET `alt_text` = REPLACE(`alt_text`, 'by Makeup by Needa', 'by Needa Beauty Lab') WHERE `alt_text` LIKE '%by Makeup by Needa';
